version: '3.8'

services:
    week1:
        container_name: week1
        build:
            context: ./week1
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        depends_on:
            - mongodb
        environment:
            MONGO_URL: mongodb://${DB_USERNAME}:${DB_PWD}@mongodb:27017/?authSource=admin
            DB_NAME: week1data
            PORT: 5000
        volumes:
            - ./week1:/app
    mongodb:
        image: mongo:latest
        container_name: mongodb
        expose:
            - "27017"
#        ports:
#            -   "27017:27017"
        volumes:
            - mongo-data:/data/db
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PWD}
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        volumes:
            - ./prometheus:/etc/prometheus
            - prometheus-data:/prometheus
        ports:
            - "9090:9090"
        command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    grafana:
        build: ./grafana
        ports:
            - "3000:3000"
volumes:
    mongo-data:
        driver: local
    prometheus-data: