global:
    scrape_interval: 3s
    evaluation_interval: 3s
    scrape_timeout: 2s

rule_files:
    - alert.yml

scrape_configs:
    - job_name: "week1"
      static_configs:
          - targets: ["week1:5000"]
    - job_name: "app2"
      static_configs:
          - targets: ["app2:5001"]