global:
    scrape_interval: 15s
    evaluation_interval: 15s
    scrape_timeout: 10s

rule_files:
    - alert.yml

scrape_configs:
    - job_name: "week1"
      static_configs:
          - targets: ["week1:5000"]