name: 'coverage app2 service'
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

defaults:
    run:
        working-directory: app2/

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                  working-directory: app2/
